### ISSUE TITLE
"exit status 128" on qpm publish

### ISSUE THREAD

**Issue by msorvig** [Cutehacks/qpm#14]
Publishing my QtS3 project (github.com/msorvig/qts3) does not seem to want to work:

$ qpm publish
email:
password: 
Running check
OK!
QPM: 2015/11/30 09:25:25 exit status 128

**Comment by jrbarron** [comment]
@msorvig Hi Morten! Hmm, strange. I just tested this with our testing server by cloning your repo and running `SERVER=pkg.qpm.io:8000 qpm publish` and everything seemed to work for me. I deleted the package so you can try the same thing. Both the production and testing server are running the same software, but use different database instances so if it works in one, it should work in the other too. You might want to check that you have the latest version of the client (v0.10.0). It shouldn't be failing without an error message though so that's a bit strange in any case. If you use Homebrew, the latest version is also available there!

**Comment by msorvig** [comment]
Got it! 

I did a "git add github git@github.com:msorvig/qts3.git" when setting up the local repo, which means there is no "origin" remote, which causes "git ls-remote" to fail.

Fixed by renaming to "origin", I should be in business now :)

**Comment by jrbarron** [comment]
Great! Still a valid bug since we should give a better error message here. I'll update the task. Thanks for publishing!

**Comment by jrbarron** [comment]
I'll just create a new issue since you closed this one ;)

**Comment by toby20130333** [comment]
@jrbarron I get the same error ,how to fix it?
Running check
OK!
QPM: 2016/05/26 10:16:22 Cannot get the last commit SHA1: exit status 128

**Comment by jrbarron** [comment]
@toby20130333 The problem you are having is slightly different than above. In this case, qpm is trying to determine the lastest Git commit that it should use for publishing. Behind the scenes, it is running this command: `git rev-parse HEAD`, but `git` is returning an error.  Could it be that you have not committed anything yet? qpm works differently from npm in that it does not store the source code itself, but rather requires that it is published to a public Github repository. Have you done that yet?
