### ISSUE TITLE
Something that should be obvious to point out.

### ISSUE THREAD

**Issue by MrHamel** [Cutehacks/qpm#29]
Does anyone else see the irony of this project being written in Go when it's for Qt?

**Comment by jrbarron** [comment]
The decision was between Node, Qt, and Go. At the end of the day, we wanted the possibility to share code between the client and server and Go's server side support is much better than Qt's so we decided to implement it in Go. Go is great for command line tools and being able to cross-compile a Windows binary from a Mac is awesome. Go's static binary approach made deployment trivial in comparison to Node so that made it a winner :)

**Comment by ElderOrb** [comment]
... but its not too late to implement list of packages using QMLWeb https://github.com/qmlweb/qmlweb when it matures enough :)
