### ISSUE TITLE
not able to build qpm

### ISSUE THREAD

**Issue by redgrapetech** [Cutehacks/qpm#33]
go build qpm.io/qpm
can't load package: package qpm.io/qpm: cannot find package "qpm.io/qpm" in any of:
        /usr/lib/go-1.6/src/qpm.io/qpm (from $GOROOT)
        /mnt/khajana/qpm/src/qpm.io/qpm (from $GOPATH)

=========== Workaround ===============
```
git submodule init
git submodule update
export GOPATH=`pwd`
export PATH=$GOPATH/bin:$PATH
mkdir -p src/qpm.io
mv qpm src/qpm.io/
mv common src/qpm.io
mv vendor/* src/ 

go build qpm.io/qpm
go install qpm.io/qpm
```
now works!.

=======================================

**Comment by jrbarron** [comment]
@redgrapetech Glad you got it working. You are clearly one of the brave souls building from the `master`  branch. We have been making some big changes in the directory structure to make things more Go-like, but haven't updated all the docs yet.

Instead of using Git directly to download the package, you should be able to simply do this:

```
export GOPATH=~/go # default in Go 1.8
go get qpm.qio/qpm
```

That should download and compile everything and place the binary in $GOPATH/bin. Go's treatment of the GOPATH environment variable is a bit strange, but it needs to be set before you can build anything really.

**Comment by redgrapetech** [comment]
Thanks above steps does install qpm in $GOPATH/bin .
If possible, please correct small typo in  'go get qpm.qio/qpm'  it should be qpm.io
in above comment.
Also i am too new to qpm (project) which would be best place to put your instructions ?
README.md ?

Regds
Mallah.

**Comment by mariusbu** [comment]
@redgrapetech yup, README.md would be the place :)
