### ISSUE TITLE
Nested dependencies are not working!

### ISSUE THREAD

**Issue by Skycoder42** [Cutehacks/qpm#38]
Apparently, qpm fails to correctly detect nested dependencies, both on the website where the packages are displayed, as well when installing!

I installed the dependency with `qpm install` and it was correctly added as dependency in the qpm.json. However, when installing this package, the now nested dependency is not automatically installed.

Do I need to add extra information? Or is it broken.

The repositories I tried to add are:
- https://github.com/Skycoder42/QtMvvmCore
- https://github.com/Skycoder42/QtMvvmSettingsCore

with the second one having a dependency to the first one.

**Comment by jrbarron** [comment]
@Skycoder42 You are in somewhat uncharted territory at the moment since the dependency stuff has not really been tested much before (you are the second package using it) :) I just checked in the database and I can see that the dependency information was correctly parsed from the `qpm.json` file, but the information is being lost when pulling it out. It seems to me like you have done everything correctly so this definitely seems like a bug in the server. I'll try to find some time to fix this in the next week or so. Sorry for the inconvenience!

**Comment by jrbarron** [comment]
There were several bugs in the server causing problems, but I think I have fixed it now. Give it a try and let me know if something is still broken ;)

**Comment by Skycoder42** [comment]
It works perfectly now, awesome :D Just two minor things:
- The website still shows no dependencies until pushing a new version of a package. But thats not really a problem, because qpm itself pulls them nonetheless. And after a few updates this will be gone.
- The dependencies are added to the `qpm.json` file of the "root" (where i'm pulling them). I guess this is desired behaviour? I don't know whats the general policy for that
